services:
  oolong-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    volumes:
      - ./oolong/content:/app/src/content
    environment:
      - NODE_ENV=development
      - API_VERSION=v0.2.0-beta.2
      - SERVER_HOST=http://localhost:3005
